version: '3.7'
services:

  mysql:
    image: mysql:8.0.18
    container_name: mysql-container
    command: --innodb_use_native_aio=0
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    volumes:
      - ./data:/var/lib/mysql

  node-app:
    build: ./gate-simulator
    image: node-app:1.0
    container_name: node
    ports:
      - '9999:9999'

  postgres:
    image: postgres:12.0-alpine
    container_name: pstg-container
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/var/lib/postgresql/datapstg